name: Despliegue Automatico a InfinityFree

on:
  push:
    branches:
      - main
      - master

jobs:
  web-deploy:
    name: Sincronizando Archivos via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Subir index.html via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/README.md
            **/.github/**
